(()=>{
 const norm=v=>String(v||"").replace(/\s+/g," ").trim();
 const clean=v=>norm(v).replace(/\$\s*\d[\d,]*(?:\.\d{1,2})?/g," ").replace(/\b(?:SOLD(?: OUT)?|FREE SHIPPING|SHIPPING INCLUDED)\b/gi," ").replace(/\s+/g," ").trim();
 const canonical=href=>{try{const u=new URL(href,location.href),m=u.pathname.match(/^\/us\/item\/([^/?#]+)/i);if(!/(^|\.)mercari\.com$/i.test(u.hostname)||!m)return null;return{id:m[1],url:`https://www.mercari.com/us/item/${m[1]}/`}}catch{return null}};
 const valid=v=>{const s=clean(v);return s.length>2&&s.length<240&&!/^(sold|sold out|like|save|share|shipping|free shipping|bundle|view item|recommended|you may also like)$/i.test(s)};
 function name(a){for(const x of[a.getAttribute("aria-label"),a.getAttribute("title"),a.querySelector("img[alt]")?.alt,a.querySelector("[aria-label]")?.getAttribute("aria-label"),a.innerText])if(valid(x))return clean(x);let n=a,c=[];for(let i=0;i<4&&n;i++,n=n.parentElement)c.push(...String(n.innerText||"").split(/\n+/).map(clean).filter(valid));c.sort((a,b)=>score(b)-score(a));return c[0]||"(请手动填写商品名)"}
 const score=s=>(/\b(?:jellycat|bear|bunny|outfit|clothes|dress|costume|plush|pin|bag|sticker)\b/i.test(s)?30:0)+Math.min(s.length,120);
 function attention(){const t=document.body?.innerText||"";if(/captcha|verify you are human|security check/i.test(t))return"Mercari 要求完成人机验证。";if(/log in|sign in/i.test(document.title+" "+t.slice(0,1500))&&!/bundle for/i.test(t))return"Mercari 登录状态可能已失效。";return""}
 function scope(){const hs=[...document.querySelectorAll("h1,h2,h3,h4,[role=heading]")],h=hs.find(x=>/items? (?:in|from) (?:this|the) bundle|bundle (?:includes|items)|included items/i.test(x.innerText||""));if(h){const n=h.closest("section,main,div");if(n&&n.querySelectorAll('a[href*="/us/item/"]').length)return{anchors:[...n.querySelectorAll('a[href*="/us/item/"]')],confidence:"high"}}const all=[...document.querySelectorAll('a[href*="/us/item/"]')],stop=hs.find(x=>/recommended|you may also like|similar items|more like this/i.test(x.innerText||""));if(stop){const y=stop.getBoundingClientRect().top+scrollY;return{anchors:all.filter(a=>a.getBoundingClientRect().top+scrollY<y),confidence:"medium"}}return{anchors:all,confidence:"low"}}
 function run(bundleId){const att=attention();if(att)return{ok:true,attention:att,bundleId,rows:[]};const cur=canonical(location.href);if(!cur||cur.id!==bundleId)return{ok:false,error:"当前页面与队列 Bundle ID 不一致"};window.scrollTo(0,document.body.scrollHeight);const s=scope(),found=new Map();s.anchors.forEach(a=>{const x=canonical(a.href);if(!x||x.id===bundleId||x.id.startsWith("b")||found.has(x.id))return;found.set(x.id,{bundle_id:bundleId,item_name:name(a),mercari_item_id:x.id,item_url:x.url,source_page:cur.url,extraction_status:s.confidence==="high"?"SUCCESS":"REVIEW"})});return{ok:true,bundleId,rows:[...found.values()],confidence:s.confidence}}
 chrome.runtime.onMessage.addListener((m,_s,reply)=>{if(m.type!=="EXTRACT_BUNDLE")return;window.scrollTo(0,document.body.scrollHeight);setTimeout(()=>reply(run(m.bundleId)),1800);return true})
})();
