const $=id=>document.getElementById(id),send=message=>chrome.runtime.sendMessage(message);
const REPORT_KEY="mercariSalesReportV2";let state,report={headers:[],rows:[]};
function parseCSV(text){const rows=[];let row=[],cell="",q=false;text=String(text).replace(/^\uFEFF/,"");for(let i=0;i<text.length;i++){const c=text[i];if(q){if(c==='"'&&text[i+1]==='"'){cell+='"';i++}else if(c==='"')q=false;else cell+=c}else if(c==='"')q=true;else if(c===','){row.push(cell);cell=""}else if(c==='\n'){row.push(cell.replace(/\r$/,""));rows.push(row);row=[];cell=""}else cell+=c}if(cell||row.length){row.push(cell);rows.push(row)}return rows}
function reportFromCSV(text){const rows=parseCSV(text),headers=rows[0].map(x=>x.trim()),ix=n=>headers.findIndex(x=>x.toLowerCase()===n.toLowerCase()),id=ix("Item Id"),title=ix("Item Title"),date=ix("Completed Date");if(id<0||title<0)throw Error("CSV 中找不到 Item Id 或 Item Title 列。");const valid=rows.slice(1).filter(r=>/^[mb]\d+$/i.test((r[id]||"").trim())),seen=new Set(),queue=[];valid.forEach(r=>{const bundleId=(r[id]||"").trim(),bundleTitle=(r[title]||"").trim();if(!/^b\d+$/i.test(bundleId)||!/^bundle for\b/i.test(bundleTitle)||seen.has(bundleId))return;seen.add(bundleId);queue.push({bundleId,bundleTitle,completedDate:date>=0?(r[date]||""):""})});return{headers,rows:valid,queue}}
const esc=v=>'"'+String(v??"").replace(/"/g,'""')+'"';
function download(name,header,rows){const csv=[header,...rows].map(r=>r.map(esc).join(",")).join("\r\n"),url=URL.createObjectURL(new Blob(["\uFEFF"+csv],{type:"text/csv;charset=utf-8"}));chrome.downloads.download({url,filename:name,saveAs:true},()=>setTimeout(()=>URL.revokeObjectURL(url),5000))}
function render(s){state=s;const q=s.queue||[],finished=q.filter(x=>["done","review"].includes(x.status)).length,issues=q.filter(x=>["failed","attention","review"].includes(x.status)).length;$("total").textContent=q.length;$("done").textContent=finished;$("pending").textContent=q.filter(x=>["pending","retry","loading"].includes(x.status)).length;$("issues").textContent=issues;$("message").textContent=s.message||"";$("bar").style.width=(q.length?Math.round(q.filter(x=>["done","review","failed"].includes(x.status)).length/q.length*100):0)+"%";$("start").disabled=!q.length||s.status==="running";$("pause").disabled=s.status!=="running";$("retry").disabled=!issues;$("export").disabled=!(s.results||[]).length;$("exportQueue").disabled=!q.length;$("queue").innerHTML=q.map(x=>`<div class="qrow"><span>${x.bundleId}<br>${x.bundleTitle||""}</span><span class="${x.status}">${x.status}${x.error?" ⚠":""}</span></div>`).join("")}
async function refresh(){const [r,stored]=await Promise.all([send({type:"GET_STATE"}),chrome.storage.local.get(REPORT_KEY)]);report=stored[REPORT_KEY]||{headers:[],rows:[]};if(r?.state)render(r.state)}
$("file").addEventListener("change",async e=>{try{const f=e.target.files[0];if(!f)return;const r=reportFromCSV(await f.text());if(!r.queue.length)throw Error("没有找到 Bundle 订单。");report={headers:r.headers,rows:r.rows};await chrome.storage.local.set({[REPORT_KEY]:report});await send({type:"IMPORT_QUEUE",queue:r.queue});$("importInfo").textContent=`已导入 ${r.rows.length} 笔订单，其中 ${r.queue.length} 笔 Bundle：${f.name}`;await refresh()}catch(e){$("importInfo").textContent=e.message}});
$("start").onclick=async()=>{await send({type:"START"});refresh()};$("pause").onclick=async()=>{await send({type:"PAUSE"});refresh()};$("retry").onclick=async()=>{await send({type:"RETRY_FAILED"});refresh()};
$("clear").onclick=async()=>{if(confirm("确定清空当前队列和提取结果吗？")){await Promise.all([send({type:"CLEAR"}),chrome.storage.local.remove(REPORT_KEY)]);refresh()}};
function exportBundles(){const q=new Map(state.queue.map(x=>[x.bundleId,x])),h=["bundle_id","bundle_title","completed_date","item_name","mercari_item_id","item_url","source_page","extraction_status"];download("mercari_bundle_items_combined.csv",h,state.results.map(r=>{const x=q.get(r.bundle_id)||{};return[r.bundle_id,x.bundleTitle||"",x.completedDate||"",r.item_name,r.mercari_item_id,r.item_url,r.source_page,r.extraction_status]}))}
function exportAll(){if(!report.rows.length){alert("缺少原始 Sales Report，请重新导入后再导出全部商品。");return}const ix=n=>report.headers.findIndex(x=>x.toLowerCase()===n.toLowerCase()),id=ix("Item Id"),title=ix("Item Title"),sold=ix("Sold Date"),completed=ix("Completed Date"),status=ix("Order Status"),byBundle=new Map();state.results.forEach(r=>{if(!byBundle.has(r.bundle_id))byBundle.set(r.bundle_id,[]);byBundle.get(r.bundle_id).push(r)});const h=["order_type","parent_order_id","sold_date","completed_date","original_item_title","sold_item_name","sold_item_id","sold_item_url","extraction_status","order_status","quantity"],rows=[];report.rows.forEach(r=>{const orderId=r[id]||"",original=r[title]||"",base=[orderId,sold>=0?r[sold]:"",completed>=0?r[completed]:"",original];if(orderId.startsWith("b")){const items=byBundle.get(orderId)||[];if(items.length)items.forEach(x=>rows.push(["BUNDLE",...base,x.item_name,x.mercari_item_id,x.item_url,x.extraction_status,status>=0?r[status]:"",1]));else rows.push(["BUNDLE",...base,"","",`https://www.mercari.com/us/item/${orderId}/`,"MISSING",status>=0?r[status]:"",1])}else rows.push(["NORMAL",...base,original,orderId,`https://www.mercari.com/us/item/${orderId}/`,"NOT_APPLICABLE",status>=0?r[status]:"",1])});download("mercari_all_sold_items_for_cost_mapping.csv",h,rows)}
$("export").onclick=()=>{const mode=document.querySelector('input[name="exportMode"]:checked')?.value||"bundle";mode==="all"?exportAll():exportBundles()};
$("exportQueue").onclick=()=>download("mercari_bundle_extraction_status.csv",["bundle_id","bundle_title","completed_date","status","attempts","error"],state.queue.map(x=>[x.bundleId,x.bundleTitle,x.completedDate,x.status,x.attempts,x.error]));
chrome.runtime.onMessage.addListener(m=>{if(m.type==="STATE_UPDATED")refresh()});refresh();
